name: discord-downdetector

on:
  push:
    branches:
      #- main
      - "*"
    tags:
      #- v*
      - "*"

env:
  REPOSITORY:         ${{ github.event.repository.name }}
  GITHUB_REF:         ${{ github.ref }}
  COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
  DOCKER_USER:        ${{ secrets.DOCKER_USER }}
  DOCKER_SECRET:      ${{ secrets.DOCKER_SECRET }}

jobs:
  dagger:
    name: Build the image with Dagger
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          cmds: |
            project init
            project update
            do push
