name: discord-downdetector

on:
  push:
    branches:
      - main

env:
  DOCKER_USER:   ${{ secrets.DOCKER_USER }}
  DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
  REPOSITORY:    ${{ github.event.repository.name }}

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          cmds: |
            project update
            do load